# Generated by Django 4.0.4 on 2022-05-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supply',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
