# Generated by Django 4.0.4 on 2022-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_cnpj_user_cpf_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bananas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
